baseURL = 'https://www.cflidgren.info/'
languageCode = 'en-us'
title = 'Carl-Fredrik Lidgren'
#theme = "PaperMod"

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

[markup.goldmark.parser.attribute]
block = true


[params]
  defaultTheme = "dark"

  # [params.assets]
  # theme_color = "#330500"

  [params.homeInfoParams]
  Title = "Carl-Fredrik Lidgren"
  Content = "Personal website"

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/cflidgren"

  [[params.socialIcons]]
  name = "Bandcamp"
  url = "https://gren.bandcamp.com"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:carl.fredrik.lidgren@gmail.com"

  [params.profileMode]
  enabled=true
  subtitle='Mathematician & Musician'

  [[params.profileMode.buttons]]
  name = "About Me"
  url = "/about-me"

  [[params.profileMode.buttons]]
  name = "Writings"
  url = "/writings"

  [[params.profileMode.buttons]]
  name = "Music"
  url = "/music"

[[menu.main]]
  identifier = "about-me"
  name = "About Me"
  url = "/about-me"
  weight = 10

[[menu.main]]
  identifier = "writings"
  name = "Writings"
  url = "/writings"
  weight = 20

[[menu.main]]
  identifier = "music"
  name = "Music"
  url = "/music"
  weight = 30

